name: Build and deploy Node.js app to Azure Web App - turism-valcea

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install frontend dependencies and build React
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Copy React build to backend
        run: |
          robocopy frontend\build backend\build /E
          exit 0
        shell: cmd
        
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Debug secrets
        run: |
          echo "Client ID is set? ${{ secrets.AZUREAPPSERVICE_CLIENTID != '' }}"
          echo "Tenant ID is set? ${{ secrets.AZUREAPPSERVICE_TENANTID != '' }}"
          echo "Subscription ID is set? ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID != '' }}"
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3172DA5556FC4AAAAC0992D58DBF4BAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0D2B02493235420998A64F9FF39C4FB6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_735BC98F21E545139B292E05BD58EE63 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'turism-valcea'
          slot-name: 'Production'
          package: .
          
